### ISSUE TITLE
Quotes around search string

### ISSUE THREAD

**Issue by pribilinskiy** [anephew/brackets-zeal#2] opened 2014-11-16 15:23 UTC
Search is not performed because Zeal obtains the query with unnecessary single quotes
![3kol5gz 1](https://cloud.githubusercontent.com/assets/3078595/5061911/0b5b6e04-6db5-11e4-974a-289dfbfb20ed.png)

**Comment by GandalfTheCoder** [comment] 2015-03-10 20:08
Pull request submitted with fix for this.

**Comment by FlouksBerlin** [comment] 2015-05-08 14:17
Still not fixed? :/

**Comment by GandalfTheCoder** [comment] 2015-05-15 23:18
Not sure why, but my pull request was denied. Looks like they don't want it
fixed.

Nathan

**Comment by g1ps** [comment] 2015-07-14 07:31
Thanks for the fix. I applied it to my local copy and it works just fine. Please re-submit your pull request, it's cleearly needed.

Cheers.

**Comment by abdelouahabb** [comment] 2015-11-27 17:58
confirmed the issue here.

**Comment by casterle** [comment] 2016-04-13 19:33
g1ps, would you please post the code/instructions to fix this issue here?

**Comment by Xhynk** [comment] 2016-04-15 20:25
@casterle - In the <os:>\Users\<user>\AppData\Roaming\Brackets\extensions\user\anephew.brackets-zeal\node folder is the ZealDomain.js file.

Change line 26 from:
`    child_process.exec("zeal --query '" + str + "'", function (error, stdout, stderr) {`
- to -
`    child_process.exec("zeal --query " + str, function (error, stdout, stderr) {`

You see I've just removed the single quotes from that `.exec` function.

**Comment by casterle** [comment] 2016-04-15 21:06
Thank you!

**Closed** 2016-04-15 22:09 UTC
